version: "3.8"

services:
  test:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    depends_on:
      - agent
    volumes:
      - ../volumes/tmp/cache:/cache
      - ../volumes/build:/build
      - ../volumes/reports:/reports
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports
    networks:
      db:

  builder:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../volumes/tmp/cache:/cache
      - ../volumes/build:/build
      - ../volumes/target:/wheelhouse
    entrypoint: "entrypoint.sh"
    command: ["pip", "wheel", "--no-index", "-f /build", "."]

  agent:
    image: jmenga/ansible
    build:
      context: ../../../
      dockerfile: ./docker-ansible/Dockerfile
    depends_on:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    command: ["probe.yml"]
    volumes:
      - ../../ansible/:/ansible/
    networks:
      db:

  db:
    image: mysql:5.6
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      db:

  cache:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../volumes/tmp/cache:/cache
      - ../volumes/build:/build
    entrypoint: "true"

networks:
  db:
